const charactersNames = [
  "22",
  "A Baleia (Procurando Nemo)",
  "A Bruxa (Valente)",
  "Abuelita (Viva: A Vida é uma Festa)",
  "Acer",
  "Aiken Axler",
  "Alegria",
  "Alfredo Linguini",
  "Alpha",
  "Anchor",
  "Andy Davis",
  "Angus",
  "Arlo",
  "Arrasador",
  "Art",
  "Atta",
  "Autofone",
  "Bailey",
  "Bala no Alvo",
  "Barbie",
  "Barley Lightfoot",
  "Barracuda",
  "Beta e Gamma",
  "Betty",
  "Big D",
  "Bill",
  "Bill Andersen",
  "Billy Oilchanger",
  "Bing Bong",
  "Bob",
  "Bob Cutlass",
  "Bolha",
  "Bonnie Anderson",
  "Boo",
  "Boost",
  "Brasinha",
  "Brian Spark",
  "Brick",
  "Brick Yardley",
  "Bruce",
  "Brush Curber",
  "Bubba",
  "Bubbha",
  "Buck (O Bom Dinossauro)",
  "BURN-E (personagem)",
  "Buster (Toy Story)",
  "Butch (O Bom Dinossauro)",
  "Buzz Lightyear",
  "Cal Weathers",
  "Cardume",
  "Carl Fredricksen",
  "Carla Veloso",
  "Celia Mae",
  "Charles Muntz",
  "Charlie (Procurando Dory)",
  "Chick Hicks",
  "Chucrute",
  "Chum",
  "Cocó",
  "Colette Tatou",
  "Colt Bronco",
  "Coral",
  "Corey a Manticora",
  "CR",
  "Crush",
  "Cruz Ramirez",
  "Dale Earnhardt JR (carro)",
  "Daniel Swervez",
  "Dante",
  "Darrel Cartrip",
  "Darren Leadfoot",
  "Dean Hardscrabble",
  "Destiny",
  "Dirkson D'Agostino",
  "Doc Hudson",
  "Don Carlton",
  "Dory",
  "Dot",
  "Dragões",
  "Dud Throttleman",
  "Dug",
  "Duke Caboom",
  "Earl",
  "Edna Moda",
  "Ellie Fredricksen",
  "Elétrico",
  "Emile",
  "Emoções da Sra. Andersen",
  "Emoções do Sr. Andersen",
  "Eric Roadales",
  "Ernesto de la Cruz",
  "Ernie Gearson",
  "Esguicho",
  "Esguicho (Os Incríveis)",
  "Estica (Toy Story)",
  "Eugene Carbureski",
  "EVA",
  "Evelyn Deavor",
  "Família das Cavernas",
  "Ferrugem",
  "Fillmore (Carros)",
  "Finn McMissil",
  "Flecha Pêra",
  "Flik",
  "Flip Dover",
  "Flo",
  "Forrest Woodbush",
  "Francesco Bernoulli",
  "Frank",
  "Frida Kahlo",
  "Fúlvio e Rubens",
  "Gabby Gabby",
  "Garfinho",
  "Gelado",
  "Geraldo",
  "Geri",
  "Gill",
  "Gluglu",
  "Gray (Carros)",
  "Greg Candyman",
  "Guido",
  "Hank",
  "Hannah Phillips",
  "Harris, Hubert e Hamish",
  "Hipnotizador",
  "Holley Caixadibrita",
  "Homenzinhos Verdes",
  "Hopper",
  "Héctor Rivera",
  "Ian Lightfoot",
  "Imelda",
  "Imperador Zurg",
  "Beto Pêra",
  "Jack DePost",
  "Jackson Storm",
  "James Cleanair",
  "James P. Sullivan",
  "Jan Flash Nilsson",
  "Jenny (Procurando Dory)",
  "Jessie",
  "Jill Andersen",
  "Jimbo (Carros 3)",
  "Jimmy Cables",
  "Joe Gardner",
  "Johnny Worthington III",
  "Jordan (Divertida Mente)",
  "Jovem MacGuffin",
  "Jovem Macintosh",
  "Ken Carson",
  "Kevin Racingtire",
  "Lagarto Feitiçeiro",
  "Lane Locke",
  "Laurel Lightfoot",
  "Leroy Heming",
  "Libby",
  "Lista de Vilões da Pixar",
  "Lizzie (Carros)",
  "Lorde Dingwall",
  "Lorde MacGuffin",
  "Lorde Macintosh",
  "Lotso, O Ursinho Fofo",
  "Louise''Nada''Modesta",
  "Luigi",
  "Lurleane",
  "M-O",
  "Mack",
  "Mamá Inês",
  "Mamãe Ida",
  "Marlin",
  "Mate",
  "Maudie",
  "Medo",
  "Meg (Divertida Mente)",
  "Melancolia",
  "Melvin",
  "Miguel Rivera",
  "Mike Wazowski",
  "Miles Eixodarroda",
  "Mirage (Os Incríveis)",
  "Misti Motorkross",
  "Molt",
  "Mor'du",
  "Mulher Elástica",
  "Mérida",
  "Nash e Ramsey",
  "Natalia Certeza",
  "Nemo",
  "Nojinho",
  "O Corvo",
  "O Rei",
  "O Sorveteiro",
  "Olho-Vivo",
  "Papai Henry",
  "Patinho e Coelhinho",
  "Peach (Procurando Nemo)",
  "Pepita",
  "Pete Fedido",
  "Ponchy Wipeout",
  "Porquinho",
  "Professor Knight",
  "Professor Zundapp",
  "Rainha Elinor",
  "Rainha Netuna (Toy Story)",
  "Raiva",
  "Ramone",
  "Randall Boggs",
  "Rei Fergus",
  "Relâmpago McQueen",
  "Remy",
  "Rex",
  "Riley Andersen",
  "River Scott",
  "Rod Torque Redline",
  "Ronald (Carros 3)",
  "Roz",
  "Ruivo",
  "Russell",
  "Ryan Shields",
  "Sally Carrera",
  "Sargento (Toy Story)",
  "Scott Squibbles",
  "Sid Phillips",
  "Slim",
  "Slinky",
  "Smokey",
  "Speedy Comet",
  "Spot (O Bom Dinossauro)",
  "Sr. Anderson",
  "Sr. Cabeça-de-Batata",
  "Sr. Espeto",
  "Sra. Anderson",
  "Sra. Cabeça-de-Batata",
  "Sra. Davis",
  "Stanley (Carros)",
  "Síndrome",
  "T-Bone",
  "Ted",
  "Tempestade (O Bom Dinossauro)",
  "Terri e Terry Perry",
  "Tex (THX)",
  "Tex Dinoco",
  "Thumper",
  "Tio Raia",
  "Todd (Carros)",
  "Tristeza",
  "Trixie",
  "Unicórnio Arco-Íris",
  "Violeta Pêra",
  "Voide",
  "WALL-E (personagem)",
  "Wee Dingwall",
  "Wheezy",
  "Wilden Lightfoot",
  "Will o Wisps",
  "Wingo",
  "Winston Deavor",
  "Woody",
  "Xerife (Carros)",
  "Yeti (Monstros S.A.)",
  "Zezé Pêra",
];

module.exports = charactersNames;
